import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsDateString,
  IsNumber,
  IsOptional,
  IsPositive,
  IsUUID,
  ValidateNested,
} from 'class-validator';

export class AppointmentItemUsageDto {
  @ApiPropertyOptional({
    format: 'uuid',
    description:
      'Idempotency key generated by the app (ADR-09). Resending a line with the same key returns the movement already recorded instead of deducting the stock again.',
  })
  @IsOptional()
  @IsUUID()
  clientGeneratedId?: string;

  @ApiProperty({ example: '3f7b1c4a-8e2d-4f1a-9c3b-2d4e5f6a7b8c' })
  @IsUUID()
  itemId!: string;

  @ApiProperty({ example: 2, description: 'Quantity used, in the item unit' })
  @IsNumber({ maxDecimalPlaces: 3 })
  @IsPositive()
  quantity!: number;

  @ApiPropertyOptional({
    example: '2026-09-25T13:05:00.000Z',
    description:
      'When the item was actually consumed. Lets an offline client preserve the real consumption time instead of the sync time; defaults to the appointment `startsAt` when omitted.',
  })
  @IsOptional()
  @IsDateString()
  occurredAt?: string;
}

// No `userId`: the owner comes from the token, never from the request (ADR-11).
export class RegisterAppointmentItemsDto {
  @ApiProperty({ type: [AppointmentItemUsageDto] })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(100)
  @ValidateNested({ each: true })
  @Type(() => AppointmentItemUsageDto)
  items!: AppointmentItemUsageDto[];
}
