import { ConfigService } from '@nestjs/config';

import { TokenUse } from './cognito-claims';

/**
 * The Cognito settings the guard needs, read once at startup.
 *
 * `COGNITO_*` is generated by `npm run dev:bootstrap` into `.aws-local.env`
 * (see docs/ambiente-local.md). In production the same names come from the
 * environment.
 */
export interface CognitoConfig {
  jwksUri: string;
  issuer: string;
  clientId: string;
  acceptedTokenUse: readonly TokenUse[];
  subCacheTtlMs: number;
  subCacheMaxEntries: number;
  /** Seconds of leeway on `exp`, for phones whose clock drifts. */
  clockToleranceSec: number;
}

/**
 * Only the id token is accepted.
 *
 * The access token Cognito issues carries no `email` claim, and the local
 * mirror (ADR-02) cannot be created without one — `user.email` is NOT NULL and
 * unique. Accepting access tokens would mean calling Cognito for the e-mail on
 * every first request, which is exactly the round trip the mirror exists to
 * avoid.
 */
const ACCEPTED_TOKEN_USE: readonly TokenUse[] = ['id'];

const DEFAULT_SUB_CACHE_TTL_MS = 5 * 60 * 1000;
const DEFAULT_SUB_CACHE_MAX_ENTRIES = 10_000;
const DEFAULT_CLOCK_TOLERANCE_SEC = 5;

export function loadCognitoConfig(config: ConfigService): CognitoConfig {
  const issuer = required(config, 'COGNITO_ISSUER');
  const clientId = required(config, 'COGNITO_CLIENT_ID');

  return {
    issuer,
    clientId,
    // Real AWS serves the key set under the issuer. The emulator does not: it
    // answers at `/<pool-id>/.well-known/jwks.json` and treats the root path as
    // an S3 request (ADR-12), which is why the bootstrap writes the full URI.
    jwksUri: config.get<string>('COGNITO_JWKS_URI')?.trim()
      ? config.get<string>('COGNITO_JWKS_URI')!.trim()
      : `${issuer}/.well-known/jwks.json`,
    acceptedTokenUse: ACCEPTED_TOKEN_USE,
    subCacheTtlMs: numberOr(
      config,
      'AUTH_SUB_CACHE_TTL_MS',
      DEFAULT_SUB_CACHE_TTL_MS,
    ),
    subCacheMaxEntries: numberOr(
      config,
      'AUTH_SUB_CACHE_MAX_ENTRIES',
      DEFAULT_SUB_CACHE_MAX_ENTRIES,
    ),
    clockToleranceSec: numberOr(
      config,
      'AUTH_CLOCK_TOLERANCE_SEC',
      DEFAULT_CLOCK_TOLERANCE_SEC,
    ),
  };
}

/**
 * Missing Cognito settings stop the process instead of being discovered later.
 *
 * The alternative is a server that starts cleanly and then answers 500 to every
 * authenticated request, with the real cause three layers down in a stack trace.
 */
function required(config: ConfigService, key: string): string {
  const value = config.get<string>(key)?.trim();
  if (!value) {
    throw new Error(
      `${key} is not set. The COGNITO_* variables are written by ` +
        '`npm run dev:bootstrap` into .aws-local.env — see docs/ambiente-local.md.',
    );
  }
  return value;
}

function numberOr(
  config: ConfigService,
  key: string,
  fallback: number,
): number {
  const raw = config.get<string>(key);
  if (raw === undefined || String(raw).trim() === '') return fallback;

  const parsed = Number(raw);
  if (!Number.isFinite(parsed) || parsed < 0) {
    throw new Error(`${key} must be a non-negative number, got "${raw}".`);
  }
  return parsed;
}
