#!/bin/bash
#
# Creates or updates the production database stack (infra/database.yaml).
#
#   scripts/deploy-database.sh
#
# The first run takes ~10 minutes: RDS creates the instance before the stack
# can finish. The password is generated by Secrets Manager and never printed.
#
# Runs on your machine with your own AWS credentials (`aws login`).

set -euo pipefail

# The PUCRS account only allows us-east-2 (an organization policy denies the
# other regions), so the region is fixed rather than read from the profile.
REGION='us-east-2'
STACK='administranest-prod-database'
TEMPLATE="$(dirname "$0")/../infra/database.yaml"

VPC_ID=$(aws ec2 describe-vpcs --region "${REGION}" \
  --filters Name=is-default,Values=true --query 'Vpcs[0].VpcId' --output text)
if [ "${VPC_ID}" = 'None' ]; then
  echo 'No default VPC in us-east-2.' >&2
  exit 1
fi

aws cloudformation deploy \
  --region "${REGION}" \
  --stack-name "${STACK}" \
  --template-file "${TEMPLATE}" \
  --no-fail-on-empty-changeset \
  --tags project=administranest environment=prod \
  --parameter-overrides "VpcId=${VPC_ID}"

aws cloudformation describe-stacks --region "${REGION}" --stack-name "${STACK}" \
  --query 'Stacks[0].Outputs[].[OutputKey,OutputValue]' --output text
